# bf2c - A BrainFuck to C compiler
import sys
import os
if not ".bf" in sys.argv[1]:
	print("ERROR: File must end in .bf")
	exit(-1)
brainfuck_file = open(sys.argv[1], "r")
brainfuck_code = brainfuck_file.read().replace("\n", "")
brainfuck_file.close()
code_start = "//Generated by BF2C.\n#include <stdio.h>\nint main() {char brainfuck_memory[30000] = {0};int ptr = 0;"
mapping = {
">": "++ptr;",
"<": "--ptr;",
"+": "brainfuck_memory[ptr]++;",
"-": "brainfuck_memory[ptr]--;",
".": "putchar(brainfuck_memory[ptr]);",
",": "brainfuck_memory[ptr]=getchar();",
"[": "while (brainfuck_memory[ptr] != 0) {",
"]": "}"
}
output_code = code_start
for i in list(brainfuck_code):
	output_code = output_code + mapping[i]
output_code = output_code + 'printf("\\n");}'
output_file = open(sys.argv[1].replace('.bf', '.c'), "w")
output_file.write(output_code)
output_file.close()
